name: Create installers

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  set-version-number:
    name: Set version number
    runs-on: ubuntu-latest
    outputs:
      nuGetVersion: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
      is-release: ${{ steps.gitversion.outputs.CommitsSinceVersionSource == 0 }}
    
    steps:
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1

  build-winget:
    name: Winget - Update package manifest in the OWC
    needs:
     - set-version-number
    runs-on: windows-latest
    #if: ${{ needs.set-version-number.outputs.is-release == 'true' }}

    steps:
    - name: Winget-Create
      run: |

        $version = "$($env:version)"

        # Download wingetcreate
        iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe

        $x64Url="https://github.com/erikbra/grate/releases/download/$version/grate-msi-win-x64-$version.msi"
        $arm64Url="https://github.com/erikbra/grate/releases/download/$version/grate-msi-win-arm64-$version.msi"


        # Updating a manifest is only supported with the same number of installer URLs.
        echo "Running ./wingetcreate.exe update erikbra.grate --urls $x64Url $arm64Url -v $version -t `"$env:WINGET_GH_PAT`" "#--submit"
        ./wingetcreate.exe update erikbra.grate --urls $x64Url $arm64Url -v $version -t "$env:WINGET_GH_PAT" #--submit

        echo "Running ./wingetcreate.exe update erikbra.grate --urls $x64Url -v $version -t `"$env:WINGET_GH_PAT`" --submit"
        ./wingetcreate.exe update erikbra.grate --urls $x64Url -v $version -t "$env:WINGET_GH_PAT" --submit

      env:
        WINGET_GH_PAT: ${{ secrets.WINGET_GH_PAT }}
        version: "1.7.0"
        #version: "${{ needs.set-version-number.outputs.nuGetVersion }}"

